### ISSUE TITLE
Working example of the Disposable mixin?

### ISSUE THREAD

**Issue by cosmoKenney** [gnaeus/knockout-decorators#5]
Can you provide a fiddle or something that shows how to use the Disposable mixin? I can't get it to compile.

**Comment by gnaeus** [comment]
Example from readme can not be compiled because I forget to call `super();` from derived `constructor()`.
I fix the docs. Thanks for your reply!

And it seems that JSFiddle uses old TypeScript version that will not support mixins. They are available since TypeScrit 2.2.  So I create [working example](https://codepen.io/anon/pen/QgXxrv?editors=1010) in CodePen.

Also you can find usages of `Disposable` mixin in [this](../tree/master/test/disposable-mixin-test.ts) unit tests file.
