### ISSUE TITLE
Dependency tracking seems broken when using @computed

### ISSUE THREAD

**Issue by cosmoKenney** [gnaeus/knockout-decorators#6]
Take a look at this CodePen with decorators that shows the computed not working: https://codepen.io/cosmokenney/pen/PjMazv (edited)
Take a look at this vanilla knockout CodePen that shows the same computed working: https://codepen.io/cosmokenney/pen/owKywP

This shows a parent viewmodel that has a child model instance and the parent vm exposes a computed that totals an observable in an array in the model instance. 
Note that I can't get jsfiddle to recognize the decorators, but this code sample demonstrates the problem. 
When you change the value of the child's observable property, I'd expect the top-level parent's computed to detect the change, and show a new value. 

But with decorators applied, the totalMoney computed never changes. 
If I convert over to plan ko, using ko.computed instead of @computed, and ko.observable instead of @observable, then totalMoney updates when you change the child's testMoney observable. 

Also note that this example is a bit watered down in terms of how the custom binding works, but the results are the same.

**Comment by gnaeus** [comment]
It's not because of bug in `@computed`. It's because your `currency` binding is not truly two-way binding like `value`, `checked`, `hasFocus`, `textInput`. It does not support directly writing to ViewModel property instead of `ko.observable`.

You can rewrite your binding like this
```js
ko.bindingHandlers.currency = {
  init: (element, valueAccessor, allBindings, viewModel, bindingContext) => {
    var prop = valueAccessor();
    var propIsObs = ko.isObservable(prop) || ko.isWriteableObservable(prop);
    var newProp = ko.pureComputed({
      // marshal the value and/or format for the inputmask control
      read: () => {
        return Helpers.safeParseInt(ko.unwrap(prop), 0).toString();
      },
      write: nv => {
        var numericVal = Helpers.safeParseInt(nv, 0);
        if (propIsObs) {
          prop(numericVal);
        } else {
---    // prop = numericVal;
+++       allBindings.get("_ko_property_writers").currency(numericVal);
        }
      }
    });
    ko.bindingHandlers["value"]["init"](
      element, () => { return newProp; }, allBindings, viewModel, bindingContext
    );
  }
};

+++ ko.expressionRewriting["_twoWayBindings"].currency = true;
```
See [the Pen](https://codepen.io/anon/pen/wqwKxq?editors=1010)

If you don't want to modity your bindings, you can use the `unwrap` utility function for getting RAW `ko.observable` from an `@observable`. See [readme](https://github.com/gnaeus/knockout-decorators#knockout-decorators-unwrap)
```js
const { observable, computed, unwrap } = KnockoutDecorators;

public class TestChildModel {
  @observable testMoney: number;
  constructor( deposit: number ){
    this.testMoney = deposit;
  }
  // pass `unwrap` function to data-bindings
  unwrap(key: string) {
    return unwrap(this, key);
  }
}
```
```html
<input id="test" data-bind="currency: unwrap('testMoney')" type="text" />
```
See [the Pen](https://codepen.io/anon/pen/GvKovQ?editors=1010)

**Comment by cosmoKenney** [comment]
@gnaeus  
Okay, it is definitely preferable to handle it in the binding because I do not want to use unwrap in my view at all if I can otherwise avoid it.

Can you explain what the `allBindings.get("_ko_property_writers").currency` returns? If it's a simple observable, then I'd rather use it in closures in my computed, Pen: https://codepen.io/cosmokenney/pen/QMLdEg

**Comment by gnaeus** [comment]
`_ko_property_writers` is an API for developers of custom bindings, and it's not well documented.

Look at the following lines in Knockout source code:
https://github.com/knockout/knockout/blob/master/src/binding/expressionRewriting.js#L126
https://github.com/knockout/knockout/blob/master/src/binding/expressionRewriting.js#L148

So that `allBindings.get("_ko_property_writers").currency` contains the following function:
```js
function (_z) { testMoney = _z; }
```
It's not an `ko.observable`. It's simple setter function.   
But Knockout bindings are executed inside a wrapper like this
```js
with (myViewModelInstance) {
  <input  data-bind="currency: testMoney"/>
}
```
so `function (_z) { testMoney = _z; }` is equivalent to
```js
function (_z) { myViewModelInstance.testMoney = _z; }
```

**Comment by gnaeus** [comment]
Also, for better understanding how `_ko_property_writers` works, you can look at it's unit tests:
https://github.com/knockout/knockout/blob/master/spec/expressionRewritingBehaviors.js#L93
