### ISSUE TITLE
subscribe() doesn't work with  { notify: "always" } extender

### ISSUE THREAD

**Issue by jgidlow** [gnaeus/knockout-decorators#7]
If you add a subscription to an observable using the subscribe function from knockout-decorators the subscription will not use that observable's extenders. Here's an example that demonstrates this issue that happens if you use the notify extender and set its value to 'always' and then set the observable value to the same value again:

```
import * as ko from 'knockout';
import { observable, extend, unwrap, subscribe } from 'knockout-decorators';

class Test {

    @observable
    @extend({ notify: 'always' })
    test: string;

    constructor() {
        this.test = 'Hello!';

        subscribe(() => this.test, (value) => {
            console.log('Test updated 1');
        });

        unwrap(this, 'test').subscribe((value: string) => {
            console.log('Test updated 2');
        });

        setTimeout(() => {
            this.test = 'Hello!';
        }, 2000);
    }
}

ko.applyBindings(new Test());
```
Only the second subscription that is added with knockouts own subscribe function gets called after the timeout in this case. 

The first subscription gets fired from a new computed that doesn't have the original observable's extenders I think. So it never gets called in this case because the value didn't change to a different string.

**Comment by gnaeus** [comment]
Thanks! I will try to fix it when I find the time.

**Comment by gnaeus** [comment]
Sorry, but I can't find successful soluiton for this issue.

If we want to extract raw `ko.observable` from property getter, we need `this` argument and name of the property (like in `unwrap()` utility). But `subscribe()` utility accepts a lambda function as first argument. And we can not extract neither `this` arg nor `@observable` property name.

The only solution thai I find is storing last accessed `ko.observable` in global variable every time when we access each `@observable` property. Conceptually like this:
```js
let lastAccessedObservable;

const hidden = ko.observable;
const vm = {};
Object.defineProperty(vm, "field", {
  get: () => {
    lastAccessedObservable = hidden;
    return hidden();
  }
  set: hidden,
});

function subscribe(lambda, callback) {
  lambda();
  return lastAccessedObservable.subscribe(callback);
}
```
But this solution will leed to performance degradation. And also it breaks such case:
```js
class Order {
  @observable price: number;
  @observable count: number;
  constructor() {
    subscrbe(() => this.price * this.count, (amount) => {
      console.log("total cost:", amount);
    });
  }
}
```

Fortunately, `subscribe()` doesn't work only with `{ notify: 'always' }` extender (see unit tests: [1](https://github.com/gnaeus/knockout-decorators/blob/fef5f275a8c8be770f2711f6fb8ce8cfaa99ae18/test/extend-decorator-test.ts#L144), [2](https://github.com/gnaeus/knockout-decorators/blob/fef5f275a8c8be770f2711f6fb8ce8cfaa99ae18/test/extend-decorator-test.ts#L162)).

So I think it's better to add your workaround (using `unwrap()` instead of `subscribe()` with  `{ notify: 'always' }` extender) to the `@extend` decorator's documentation.

**Comment by jgidlow** [comment]
Yeah it looked like this would be difficult to fix using only the arguments that the subscribe function takes.

Thanks for taking a look at it though! And thank you for a great library.

**Comment by mbest** [comment]
The solution is to add the `{ notify: 'always' }` extender to the hidden computed that's created by subscribe.

**Comment by gnaeus** [comment]
Thanks! I will fix this in next release.
